### ISSUE TITLE
Bitte melden: Licht_druaßen_hinten (NEQ0XXXXX) --- HM-LC-Sw2PBU-FM --- Batterietyp fehlt im Script

### ISSUE THREAD

**Issue by MeisterTR** [Baenker/Servicemeldungen-Homematic#1]

**Comment by Baenker** [comment]
Sorry hatte ich übersehen. Weißt Du evtl wo ich einstellen kann das ich über ein Issue eine Mail bekomme?

Habe das Gerät im Script entsprechend aufgenommen. Wird aber erst im komplett überarbeiteten Script veröffentlicht

**Comment by Baenker** [comment]
Sorry hatte ich übersehen. Weißt Du evtl wo ich einstellen kann das ich über ein Issue eine Mail bekomme?

Habe das Gerät im Script entsprechend aufgenommen. Wird aber erst im komplett überarbeiteten Script veröffentlicht

**Comment by Baenker** [comment]
Habe es in beiden Version eingepflegt
