### ISSUE TITLE
Fehlender Batterietyp HmIP-DSD-PCB 

### ISSUE THREAD

**Issue by ciddi89** [Baenker/Servicemeldungen-Homematic#10]
Hallo,

das Skript meldet das beim oben genannten Objekt der Batterietyp fehlt und man es bitte melden soll. :) Hiermit tue ich das. Batterietyp sind 2x LR03/AAA.

Liebe Grüße :)

**Comment by Baenker** [comment]
Zeile 417 bei Bedarf ergänzen. Für die neue Version habe ich es entsprechend angepasst. Danke fürs melden.

**Comment by ciddi89** [comment]
> Zeile 417 bei Bedarf ergänzen. Für die neue Version habe ich es entsprechend angepasst. Danke fürs melden.

Bei mir ist es Zeile 416 "lr3x2" 🙈 Aber ist hinzugefügt. Vielen Danke für die schnelle Antwort. :)

**Comment by Baenker** [comment]
Stimmt. In der neuen Version ist die Zeile eine Zeile runtergerutscht da ich oben die Version fotgeschrieben habe :-)
