### ISSUE TITLE
Servicemeldungen werden in der VIS nebeneinander angezeigt

### ISSUE THREAD

**Issue by ZikeDE** [Baenker/Servicemeldungen-Homematic#11]
Moin,

wenn du in Zeile 1997

                setState(id_Text_Servicemeldung,servicemeldung.join(', '));    

durch

                setState(id_Text_Servicemeldung,servicemeldung.join('<br> '));   

änderst werden die Servicemeldungen untereinander anzeigt und nicht mehr durch ein Komma getrennt.

Grüße 
Jeremy

**Comment by Baenker** [comment]
Das ist mir bewusst aber warum sollte man das wollen. Man kann Problemlos in vis das Komma durch einen Zeilenumbruch ersetzen... Man könnte das auch in vis so umwandeln das nicht nur eine neue Zeile gewählt genommen wird sondern auch eine Bindestrich davor gesetzt wird oder das nur die passende Servicemeldung bei den passenden Gerät angezeigt wird. 

Die Zeile zu ersetzen ist halt quick und dirty.
