### ISSUE TITLE
ID in der Servicemeldung ausblenden

### ISSUE THREAD

**Issue by ZikeDE** [Baenker/Servicemeldungen-Homematic#12]
Moin,

wäre es möglich das ihr in der nächsten Version eine Funktion hinzufügt mit der man das schreiben der Geräte ID in die Servicemeldung ausschalten kann. Gerade wenn man die Meldungen über TTS auf z.B. Amazon Echo ausgibt ist das schon sehr nervig wenn dann die ID angesagt wird.

Grüße Jeremy

**Comment by Baenker** [comment]
Möglich wäre es aber ich werde es nicht einbauen. Mir ist der Aufwand dazu zu hoch. Ich würde das Script gerne komplett umschreiben und einiges ändern aber mir fehlt die Zeit und Lust derzeit.

Du kannst das Script jederzeit ändern. Alles was Du entfernen musst ist +' ('+id_name +')' die Teil. 

Es fängt an bei Zeile 720 und 721

formatiert_servicemeldung.push(common_name +' ('+id_name +')' + ' - <font color="red">Spannung Batterien/Akkus gering.</font> '+Batterie +datum_seit);
                            servicemeldung.push(common_name +' ('+id_name +')' + ' - Spannung Batterien/Akkus gering. '+Batterie);

Das heißt überall wo die Zeile mit formatiert_servicemeldung bzw servicemeldung beginnt entfernst Du den Teil. Dort könntest Du es auch noch etwas textlich optimieren damit es bei der Sprachausgabe besser ist...
