### ISSUE TITLE
Unisensor Batterietyp

### ISSUE THREAD

**Issue by fraeggle** [Baenker/Servicemeldungen-Homematic#13]
Hi
Ich verwende ja die HM Nachbauten. Wie/wo kann ich in deinem Script bei dieser Fehlermeldung:
javascript.0	2021-02-15 10:42:58.589	info	(4334) script.js.Dienste_System.Homematic_Servicemeldungen: Bitte melden: HB-UNI-Sensor1_prUNISEN02 (xxxxxxxxx) --- HB-UNI-Sensor1 --- Batterietyp fehlt im Script
den Batterietyp hinzufügen?

Gruß Peter

**Comment by Baenker** [comment]
In Zeile 409 und folgende muss man den Gerätetyp eintragen oder das log auskommentieren

**Comment by fraeggle** [comment]
Daaaaaaaaaanke.
Habs rein und tut.

Gruß Peter
