### ISSUE TITLE
In welche Variable werden die Servicemeldungen geschrieben?

### ISSUE THREAD

**Issue by UlliMUC** [Baenker/Servicemeldungen-Homematic#14]
Hi,

vielen lieben Dank für die Veröffentlichung des Scripts!

Ich stehe grade aber echt auf dem Schlauch. In welche Variable werden die Servicemeldungen geschrieben?
Müsste in VIS unter Objekte -> javascript.0 -> Scriptname (bei mir "CCU_Servicemeldungen") nicht die Variable sein?

**Comment by ciddi89** [comment]
Hallo, 

Laut Code müssen diese Datenpunkte selbst angelegt werden. Sieht: 

```
//Ergebnis in Datenfelder schreiben
const write_state = true;          //Schreibt die Ergebnisse der Servicemeldungen in Datenfelder. (true = schreiben, false, kein schreiben)
//nicht benutzte Felder einfach leer lassen --> var id_IST_XXX = '';
//Müssen selber als Zahl angelegt werden
const id_IST_LOWBAT = 'Systemvariable.0.Servicemeldungen.Anzahl_LOWBAT'/*Anzahl LOWBAT*/;
const id_IST_LOW_BAT = '';
const id_IST_UNREACH = 'Systemvariable.0.Servicemeldungen.Anzahl_UNREACH'/*Anzahl_UNREACH*/;
const id_IST_STICKY_UNREACH = 'Systemvariable.0.Servicemeldungen.Anzahl_STICKY_UNREACH'/*Anzahl_STICKY_UNREACH*/;
const id_IST_CONFIG_PENDING = '';
const id_IST_UPDATE_PENDING = '';
const id_IST_DEVICE_IN_BOOTLOADER = '';
const id_IST_ERROR = '';
const id_IST_ERROR_NON_FLAT_POSITIONING = '';
const id_IST_ERROR_CODE = '';
const id_IST_FAULT_REPORTING = '';
const id_IST_SABOTAGE = '';
const id_IST_Gesamt = "Systemvariable.0.Servicemeldungen.Anzahl_GESAMT"/*Anzahl_GESAMT*/;
```

Liebe Grüße

**Comment by Baenker** [comment]
Die Antwort von @ciddi89 ist korrekt. Ergänzend dazu: Ich habe mich damals dafür entschieden die Datenpunkte manuell anzulegen, da man mit Script Datenfelder immer nur unter der Javascript instanz anlegen konnte. Da ich meine Datenfelder schon immer außerhalb gepflegt habe, war das für mich der beste Weg. 

Da die Frage beantwortet wurde schließe ich das Ticket

**Comment by UlliMUC** [comment]
Ich verstehe kein Wort von dem was ihr beide mir versucht zu sagen :) Datenpunkt selbst anlegen?
D.h. Objekte -> Neu (Datenpunkt - Zahl) und das nennt man dann zB "id_IST_Gesamt"
Darin steht da die Gesamtanzahl der Servicemeldungen?

Ich dachte, in einen String werden mit dem Script alle Meldungen hintereinandergeschrieben?
Wohnzimmer.Wandthermostat -> Batterie leer
Schlafzimmer.Fensterkontakt.links -> Sabotage erkannt

usw.

Das Skript schreibt also in die oben genannten "nur" die Anzahl der jeweiligen Meldungen?

**Comment by Baenker** [comment]
Bitte die ersten Zeilen im Script lesen und dort die erstellten Datenpunkte eintragen. Es gibt für so ziemlich alles einen eigenen Datenpunkt den man nutzen kann. Es gibt einen der nur die Anzahl schreibt oder eben einen String der alle Servicemeldungen als Text schreibt und noch einige mehr. Wie Du sie nennst ist total egal. Ich würde Sie nicht id_Ist_Gesamt nennen sondern eher IST_Gesamt_Zahl oder so. Das id setze ich in meinen Scripten davor damit ich weiß wann ich ein Datenpunkt in einer Variable habe und wann ein Wert. Ist für mich besser zu lesen.

**Comment by UlliMUC** [comment]
Du hast sicher bemerkt, ich bin völlig Anfänger :/

Ich habe jetzt im Script folgende sektion angepasst:
```
//Variablen für Servicemeldung in Objekt schreiben // Wenn einer Meldung auftritt wird diese in ein Textfeld geschrieben. z. B. für vis
const write_message = true;        // true schreibt beim auftreten einer Servicemeldung die Serviemeldung in ein Objekt
const id_Text_Servicemeldung = String;  // Objekt wo die Servicemeldung hingeschrieben werden soll (String)
```
und ein Objekt definiert:
![image](https://user-images.githubusercontent.com/78802971/109556628-5bb3cf00-7ad7-11eb-8d37-866236e96d0d.png)

Scheint aber nicht zu funktionieren:
![image](https://user-images.githubusercontent.com/78802971/109556739-7dad5180-7ad7-11eb-8559-7a501bbfcc04.png)

**Comment by Baenker** [comment]
Dein String ist völlig falsch. Es muss der komplette Pfad angegeben werden. Im Script waren Beispiele wie der Pfad aussieht... Kann man eigentlich auch bequem per Button auswählen (oben rechts). Ohne Dir zu Nahe treten zu wollen würde ich Dir raten benutz das Script noch nicht. Mach erstmal die einfachen Sachen mit ioBroker und taste Dich langsam an Javascript heran. Ich befürchte das wenn Du den Pfad angegeben hast werden neue Probleme kommen. Du musst im Script die komplette Konfiguration durch gehen und entsprechend für Dich anpassen... Ich kann mir täuschen und es läuft bei Dir aber wetten würde ich nicht drauf :-))

**Comment by UlliMUC** [comment]
Dann hast du die Wetter verloren :)  Dank deiner Hinweise läuft das Script bei mir. Danke nochmals!

Eine Frage zur Zeichenkette: Die Meldungen werden ja hintereinander da rein geschrieben. Gibt es eine Möglichkeit, diese so zu formatieren, dass zwischen den Meldungen jeweils ein Zeilenumbruch eingefügt wird, damit alle Meldungen fein ordentlich untereinander stehen?

**Comment by Baenker** [comment]
Ja entweder im Script "," durch "<br>" ersetzten. Das geht in VIS aber auch oder in VIS als Array und dann eine Tabelle damit erstellen. Der beste Weg wäre nach meiner Meinung die Array Lösung. Da ich es nicht nutze, kann ich kein Beispiel geben wie es genau funktioniert.

Im Script wäre es die Zeile 2098 

setState(id_Text_Servicemeldung,servicemeldung.join(', '));

**Comment by UlliMUC** [comment]
Ich habe das Script an der hoffentlich richtigen Stelle angepasst:
![image](https://user-images.githubusercontent.com/78802971/110306582-47536300-7ffe-11eb-93e1-b386d67ab5fe.png)

**Comment by Baenker** [comment]
Bitte aktuelle Version nutzen. Es ist Zeile 2014

setState(id_Text_Servicemeldung,servicemeldung.join(', '));

ersetzen in 

setState(id_Text_Servicemeldung,servicemeldung.join('<br>'));

Wie ich schon schrieb ist das die denkbar schlechteste Lösung...
