### ISSUE TITLE
Channel ID's stimmen evtl. nicht mehr

### ISSUE THREAD

**Issue by ciddi89** [Baenker/Servicemeldungen-Homematic#15]
Hallo,

ich weiß nicht ob es was mit den letzten Update von HM-RPC zu tun hat oder evtl. ein HM update oder ähnliches. Aber ich habe gerade zufällig bemerkt das das Skript bei mir kaum noch HM Geräte abonniert hat. Der Grund war das die Channel id's in den Selektoren mit _ALARM am ende falsch waren. Mittlerweile sind die nämlich alle ohne _ALARM in den Objekten gespeichert. Nachdem ich im ganzen Script _Alarm am ende der id's entfernt habe, wurden wieder alle verfügbaren Geräte Abonniert. Vielleicht sollten andere Benutzer auch mal gucken ob es bei Ihnen der fall ist. 

LG

**Comment by Baenker** [comment]
Die ohne Alarm gab es schon immer. Die mit Alarm gibt es auch aktuell noch. Und nur diese funktionieren zuverlässig. Wenn die Selektoren verändert werden wird fuktioniert das Script nicht mehr. Die ohne Alarm kennen nur true und false. Die mit Alarm sind als Zahl gespeichert. 

Wenn bei Dir die Datenpunkte nicht richtig angelegt werden stimmt etwas in Deiner Config nicht. Außer es hätte wirklich eine Änderung am Adapter gegeben. Da ich dort im latest bin und gestern noch eine Servicemeldung bekommen habe gehe ich davon aus das es die Datenpunkte noch gibt.

**Comment by ciddi89** [comment]
Ah okay hätte ja sein können. Naja wie gesagt bei mir gibt es die Datenpunkte nicht. Nur ohne _Alarm. Habe vor zwei Wochen ioBroker neu installiert. Davor musste ich auch keine großen Veränderung im Skript machen. Bisschen komisch finde ich das nun schon. Habe nun die Selektoren im ganzen Skript verändert und nun funktioniert es wieder wie vorher und alle Datenpunkte und Nachrichten kommen auch wie sie sollen. Werde trotzdem mal gucken warum ich die Alarm states nicht habe. Groß einzustellen gibt es ja in den configs vom hm Adapter ja nicht. Trotzdem erstmal danke für die rasche Antwort.

Lg
