### ISSUE TITLE
Bestätigte Fehler (acknowledged) führen zu wiederholten Script-Meldungen

### ISSUE THREAD

**Issue by Wildbill-Z** [Baenker/Servicemeldungen-Homematic#16]
Hallo,
mir ist jetzt schon mehrfach aufgefallen, dass bestätigte Alarme, also solche die nicht mehr den Wert 0 (No_ALARM) sonern 2 (ACKNOWLEDGED) haben, vom Script immer wieder als Fehler erfasst und ausgegeben werden. Aktuell habe ich so einen Fall wieder bei einem Thermostat, es betraf aber auch schon Fenstersensoren und andere.
Am 28.02. hatte da wohl ein Datenpunkt einen Alarm, der bestätigt wurde:
![grafik](https://user-images.githubusercontent.com/35911150/110091649-f858c400-7d98-11eb-83e6-82e05bee2bdb.png)
nur erhalte ich aber bei jeder weiteren Meldung des Scripts (erfolgt bei mir via Telegram) immer eine zusätzliche Meldung über das o.g. Gerät mit undefined:

`ioBZZM, [04.03.21 22:58]
Flur Heizkörper (OEQ1698728) - Kommunikation gestört. --- seit: 04.03.21 22:57:52 Uhr
Flur Heizkörper (OEQ1698728) - Meldung über bestätigbare Kommunikationsstörung gelöscht.  --- seit: 04.03.21 22:57:52 Uhr
Küche_Heizkörper (PEQ1630502) - undefined. --- seit: 28.02.21 14:57:22 Uhr

ioBZZM, [04.03.21 23:01]
Küche_Heizkörper (PEQ1630502) - undefined. --- seit: 28.02.21 14:57:22 Uhr`

Das bleibt nun so lange, bis ich die CCU (bei mir ist es Pivccu3 auf einem Raspi) neu starte, dann springt der Wert wieder auf NO_ALARM(0) und weitere Meldungen bleiben aus.
In der CCU-Oberfläche ist nirgendwo zu sehen, dass hier noch etwas nicht passen würde. Die Servicemeldungen sind leer (wurde ja am 28.2. bereits acknowledged, also bestätigt). Nur schein das Script zu denken, ein Wert von 2 ist verschieden von 0(kein Fehler), also muss da irgendwas faul sein.

Gruss, Jürgen

**Comment by Baenker** [comment]
Das hat nichts mit dem Fault_Report zu tun. Guck mal unter 0 und dort die ALARM Datenpunkte. Irgend ein Punkt ist vermutlich nicht gefüllt also undefined.

**Comment by Wildbill-Z** [comment]
Hi,
unter 0 finde ich beim betreffenden Gerät auch nur Datenpunkte mit Wert:
![grafik](https://user-images.githubusercontent.com/35911150/110094797-81252f00-7d9c-11eb-8146-698a64336c20.png)

Da bei allen Geräten, die bislang dann so eine unfdefined-Meldung gebracht haben, die blieb, bis ich die CCU neu gestartet habe, immer ein Datenpunkt auf ACKNOWLEDGED(2) stand, denke ich schon, dass es daran liegt. Wie gesagt, nach einem CCU-Neustart springt der wieder auf NO_ALARM(0) und der Spuk hat erst einmal ein Ende.

Ich habe das Script eben mal auf DEBUG gesetzt und neu gestartet, sehe hier aber leider auch nicht weiter, welcher Datenpunkt den Fehler meldet bzw. verursacht.

`

javascript.0 | 2021-03-05 10:23:58.576 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Es gibt eine Servicemeldung: Küche_Heizkörper (PEQ1630502) - undefined. --- seit: 28.02.21 14:57:22 Uhr
-- | -- | -- | --
javascript.0 | 2021-03-05 10:23:58.576 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es werden: 811 Datenpunkte überwacht. Derzeit: 1 Servicemeldung(en).
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: registered 811 subscriptions and 0 schedules
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] meldung alt und neu geändert
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_message steht auf false
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] log_manuell: true
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Betroffen mehr als 0. Es sind 1
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.575 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 72 Geräte mit dem Datenpunkt UPDATE_PENDING.
javascript.0 | 2021-03-05 10:23:55.569 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.569 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 83 Geräte mit dem Datenpunkt CONFIG_PENDING.
javascript.0 | 2021-03-05 10:23:55.562 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.562 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 59 Geräte mit dem Datenpunkt DEVICE_IN_BOOTLOADER.
javascript.0 | 2021-03-05 10:23:55.558 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.558 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 104 Geräte mit dem Datenpunkt FAULT_REPORTING-7_ALARM. Derzeit: 1 Servicemeldung(en).
javascript.0 | 2021-03-05 10:23:55.552 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Keine Geräte gefunden mit dem Datenpunkt ERROR_NON_FLAT_POSITIONING.
javascript.0 | 2021-03-05 10:23:55.552 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.552 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 249 Geräte mit dem Datenpunkt ERROR.
javascript.0 | 2021-03-05 10:23:55.537 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.536 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 10 Geräte mit dem Datenpunkt SABOTAGE.
javascript.0 | 2021-03-05 10:23:55.535 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.535 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 70 Geräte mit dem Datenpunkt STICKY_UNREACH.
javascript.0 | 2021-03-05 10:23:55.503 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.503 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 83 Geräte mit dem Datenpunkt UNREACH.
javascript.0 | 2021-03-05 10:23:55.497 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.497 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 13 Geräte mit dem Datenpunkt LOW_BAT.
javascript.0 | 2021-03-05 10:23:55.495 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] Variable write_state steht auf false
javascript.0 | 2021-03-05 10:23:55.494 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 68 Geräte mit dem Datenpunkt LOWBAT.
javascript.0 | 2021-03-05 10:23:55.482 | info | (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Script manuell gestartet. (Version: 1.82)

`

Gruss, Jürgen

**Comment by Baenker** [comment]
Was steht im Datenpunkt:

(1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 104 Geräte mit dem Datenpunkt FAULT_REPORTING-7_ALARM. Derzeit: 1 Servicemeldung(en).

Ist leider im ersten Screenshot überdekct...

**Comment by Wildbill-Z** [comment]
Im Log kommt bei voll aktiviertem DEBUG das hier beim Heizkörpder_Küche:
`2021-03-05 10:26:25.378  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 56 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING --- Status: 0 keine Störung --- seit: 28.02.21 16:54:08 Uhr
2021-03-05 10:26:25.378  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 57 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-1_ALARM --- Status: 0 undefined
2021-03-05 10:26:25.378  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 58 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-2_ALARM --- Status: 0 undefined
2021-03-05 10:26:25.378  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 59 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-3_ALARM --- Status: 0 undefined
2021-03-05 10:26:25.379  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 60 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-4_ALARM --- Status: 2 undefined --- seit: 28.02.21 14:57:22 Uhr
2021-03-05 10:26:25.379  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 61 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-5_ALARM --- Status: 0 undefined
2021-03-05 10:26:25.379  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 62 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-6_ALARM --- Status: 0 undefined
2021-03-05 10:26:25.379  - [32minfo[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Geräte Nr. 63 Name: Küche_Heizkörper (PEQ1630502) --- HM-CC-RT-DN --- Typ: FAULT_REPORTING-7_ALARM --- Status: 0 undefined`

Exakt die gleichen Meldungen kommen so auch für alle anderen Thermostate.
In den Objekten sieht es so aus (auch gleich zu den anderen Geräten):
![grafik](https://user-images.githubusercontent.com/35911150/110096555-4cb27280-7d9e-11eb-81c6-204db9b21fbb.png)
Der einzige für mich sichtare Unterschied ist der mit hm-rpc.0.PEQ1630502.4.FAULT_REPORTING-4_ALARM der eben ACKNOWLEDGED(2) anzeigt.

Gruss, Jürgen

**Comment by Baenker** [comment]
probier mal die neue Version

**Comment by Wildbill-Z** [comment]
Sieht gut aus. Das kommt jetzt im Log wenn ich nach FAULT_REPORTING suche:
`2021-03-05 17:05:52.337  - ^[[32minfo^[[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: Es gibt: 104 Geräte mit dem Datenpunkt FAULT_REPORTING.
2021-03-05 17:05:52.337  - ^[[32minfo^[[39m: javascript.0 (1602) script.js.Benachrichtigung.HM-Servicemeldungen: [DEBUG] id_IST Feld für FAULT_REPORTING nicht gefüllt
`
Hab dafür im Script DEBUG, find_bug und show_each_device auf true gemacht. Dann beobachte ich mal die nächsten Tage weiter, mache das Issue aber mal zu.
Vielen Dank.

Gruss, Jürgen
