### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by fenderlein** [Baenker/Servicemeldungen-Homematic#18]
Hallo,

die Installation des Adapters im IOBroker schlägt immer fehl. 
Hier mal die Ausgabe bei der Installation.

`$ ./iobroker url "https://github.com/Baenker/Servicemeldungen-Homematic" --debug
install Baenker/Servicemeldungen-Homematic#1a1cc95ba896458a2f4a4248154b1e80eaacca4b
NPM version: 6.14.12
npm install Baenker/Servicemeldungen-Homematic#1a1cc95ba896458a2f4a4248154b1e80eaacca4b --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-05-10T18_57_30_666Z-debug.log
ERROR: host.raspi-iobroker Cannot install Baenker/Servicemeldungen-Homematic#1a1cc95ba896458a2f4a4248154b1e80eaacca4b: 1
ERROR: process exited with code 25`

Danke schonmal.

**Comment by Baenker** [comment]
Die Installation muss fehlschlagen, da dies kein Adapter ist sondern einfach nur ein Script. Man nutzt den Javascript und legt dort ein Script an. Mittels paste & Copy den Code einfügen und fertig. Ich vermute Du bist neu auf dem Gebiet ioBroker? Ich würde Dir dann empfehlen erstmal die Finger von diesem Script zu lassen und dich erstmal mit einfacheren Sachen zu beschäftigen. Ist nicht böse gemeint aber das Script ist doch relativ komplex und nur wenn Dein System sauber installiert wurde und Du ein paar Objekte anlegst wird das Script wie gewünscht laufen.
