### ISSUE TITLE
Unbekannter Gerätetyp: HmIP-SWDM-B2

### ISSUE THREAD

**Issue by BoehserWolf** [Baenker/Servicemeldungen-Homematic#2]
Bitte melden: SchiebetuerRechts (0015599396340D) --- HmIP-SWDM-B2 ---

**Comment by Baenker** [comment]
> Bitte melden: SchiebetuerRechts (0015599396340D) --- HmIP-SWDM-B2 ---

Welche Batterie wird benötigt? Ist das eine AAA?

**Comment by BoehserWolf** [comment]
2 Batterien Typs AAA.

**Comment by Baenker** [comment]
Danke. In Version 1.44 aufgenommen
