### ISSUE TITLE
Script funktioniert nicht mehr

### ISSUE THREAD

**Issue by ciddi89** [Baenker/Servicemeldungen-Homematic#20]
Hallo @Baenker ,

vielleicht kannst du mir helfen. Mir ist aufgefallen das das Script schon länger nicht mehr läuft bei mir. Und zwar kommt beim Starten immer der Fehler: 

15:51:05.288 | error | javascript.0 (519) script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung: TypeError: Cannot read property 'TYPE' of undefined
-- | -- | --
15:51:05.288 | error | javascript.0 (519) at script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:620:93
15:51:05.288 | error | javascript.0 (519) at Servicemeldung (script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:607:20)
15:51:05.288 | error | javascript.0 (519) at script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:2146:5
15:51:05.288 | error | javascript.0 (519) at script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:2149:3

Außerdem wird mir im Codeeditor in der Zeile 1918 die if Abfrage ob ein Objekt angegeben ist für die Variabel 'id_Text_Servicemeldung' als fehlerhaft angezeigt und das dieser Wert immer ein false ausgeben wird. 

<img width="908" alt="Bildschirmfoto 2021-10-19 um 15 57 49" src="https://user-images.githubusercontent.com/66088020/137928832-bc2881ce-cebc-47fa-a216-3d1c5bb29d01.png">

Außer die Datenfelder im Header des Scripts wurde nichts geändert. Habe auch 1-2 mal noch neu das Script aus Github komplett neu eingefügt aber trotzdem kommen immer die Fehler.

Javascriptversion: 5.2.8
Admin: 5.1.25
Und der Rest ist auch Up to Date. Vielen dank schon mal.

Christian

**Comment by Baenker** [comment]
Der Fehler in Zeile 1918 könnte wirklich ein Fehler sein. Muss ich prüfen wenn ich an einen PC sitze. Der Rest hat damit nichts zu tun und muss ein Problem an Deinen ioBroker sein. Habe dort aber spontan auch keine Idee was es sein kann. Ich würde ja irgendwie wieder vermuten das ein Objekt nicht existiert oder noch im Speicher vom javascript Adapter ist. IoBroker wurde schon neu gestartet?

**Comment by ciddi89** [comment]
Danke für die schnelle Antwort. Sry hatte vergessen das ich das Changelog entfernt hatte. Das sollte aber nicht das problem sein. Mit Changelog gibt er diese Zeilen an:

18:35:34.598 | error | javascript.0 (519) script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung: TypeError: Cannot read property 'TYPE' of undefined
-- | -- | --
18:35:34.599 | error | javascript.0 (519) at script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:725:93
18:35:34.599 | error | javascript.0 (519) at Servicemeldung (script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:712:20)
18:35:34.599 | error | javascript.0 (519) at script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:2251:5
18:35:34.599 | error | javascript.0 (519) at script.js.Benachrichtigungen_Telegram.Homematic.HM_Servicemeldung:2254:3

Das Feld von der Variabel 'id_Text_Servicemeldung' ist gefüllt. Zeigt der Mouseover ja auch an. Datenpunkte hatte ich auch schon die alten entfernt und extra neue erstellt. Brachte auch kein erfolg. Das Script lief ja eine Zeit lang ohne Probleme. Dann irgendwann nicht mehr. Hatte jetzt vor zwei Wochen ioBroker auf ein neues System installiert ohne eine Backup Einspielung aber der Fehler ist trotzdem noch da. Komme leider jetzt erst dazu mich damit zu beschäftigen und auf Fehlersuche zu gehen. Trotzdem danke. Vielleicht finde ich ja noch das Problem.
