### ISSUE TITLE
Meldungen im Log: UPDATE_PENDING_ALARM, CONFIG_PENDING_ALARM, SABOTAGE_ALARM fehlen bei HM-IP Gerät

### ISSUE THREAD

**Issue by MarkSau** [Baenker/Servicemeldungen-Homematic#21]
Hallo, Ich nutze die V1.87 Version. 
Wenn ich das Script starte kommen folgende Meldungen für eines meiner HM-IP Geräte

<html>
<body>

javascript.0 | 2021-10-20 11:03:53.959 | warn | Object "hm-rpc.1.0009170993339E.0.UPDATE_PENDING_ALARM" does not exist
-- | -- | -- | --
javascript.0 | 2021-10-20 11:03:53.947 | warn | Object "hm-rpc.1.0009170993339E.0.CONFIG_PENDING_ALARM" does not exist
javascript.0 | 2021-10-20 11:03:53.926 | warn | Object "hm-rpc.1.0009170993339E.0.SABOTAGE_ALARM" does not exist

</body>
</html>

Die Meldungen stimmen, die Datenpunkte existieren tatsächlich nicht. Da ich aber weitere HM-IP Geräte habe, bei denen die DPs ebenfalls fehlen, wundert es mich, dass nur dieses eine Geräte angemeckert wird.
Es handelt sich um einen HmIP-SMI Bewegungsmelder.

**Comment by Baenker** [comment]
Dein Screenshot zeigt genau Dein Problem. Du hast nicht die Datenpunkte. LOW_BAT_ALARM sollte der Datenpunkt heißen.

Gleiches gilt für alle anderen Meldungen...

Entweder Adapter nicht richtig konfiguriert oder alle Adapter stoppen. Alle Datenpunkte löschen. Adapter starten und danach Script wieder starten.

Ich habe keine Ahnung warum die Datenpunkte nicht existieren. Nur ohne die Datenpunkte kann das Script nicht laufen.

**Comment by Baenker** [comment]
Ich mach hier mal zu. Seit 11 Tagen keine Reaktion. Fehler hat aber auch nichts mit dem Script zu tun.
