### ISSUE TITLE
Fehlendes Gerät HmIP-WRCD

### ISSUE THREAD

**Issue by viper4gh** [Baenker/Servicemeldungen-Homematic#22]
Hi,
erst einmal danke für das Skript.

Beim Start bekomme ich folgende Meldung:

> Bitte melden: WZ Display (002A5A498E9C10) --- HmIP-WRCD --- Batterietyp fehlt im Script

Könntest du das Gerät hinzufügen. Danke.

**Comment by Baenker** [comment]
Welche Batterie gehört denn darein?

**Comment by viper4gh** [comment]
LR03/Micro/AAA

**Comment by Baenker** [comment]
1 oder 2? Werde es in einer der kommenden Versionen einbauen

**Comment by viper4gh** [comment]
2 Batterien

**Comment by Baenker** [comment]
habe es aufgenommen. Script wird dann irgend veröffentlicht.
