### ISSUE TITLE
Log Message "Batterietyp fehlt im Script"

### ISSUE THREAD

**Issue by wiwohl** [Baenker/Servicemeldungen-Homematic#23]
On startup there is the message:

"Bitte melden: S_Raumthermostat_Wohnzimmer (xxxxxxxxxx) --- HmIP-WTH-B --- Batterietyp fehlt im Script"

2 AA type batteries are used for HmIP-WTH-B

**Comment by Mrealea** [comment]
"Bitte melden: xxx(xxxx) --- HmIP-STE2-PCB --- Batterietyp fehlt im Script" 
-> 2x AA OR fixed

"Bitte melden: xxx (xxxx) --- HmIP-WRCR --- Batterietyp fehlt im Script"
-> 2x AA

**Comment by Baenker** [comment]
In der nächsten Version aufgenommen
