### ISSUE TITLE
Liste der Servicemeldungen untereinander funktioniert nicht

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Baenker/Servicemeldungen-Homematic#28]
Ich habe einen Inhalt im neuen iOBroker-Datenpunkt hm-rega.0.5153: "NEUE Servicemeldung%0D%0AFREI : %0D%0Ahat Kommunikationsfehler %0D%0A1 mal seit: 22.09.22 01:51 ( zuletzt: 22.09.22 01:51)%0D%0A%0D%0AFREI 1 : %0D%0Ahat Kommunikationsfehler %0D%0A1 mal seit: 22.09.22 01:51 ( zuletzt: 22.09.22 01:51)%0D%0A%0D%0A".
Aber eine zeilenweise Darstellung in einem Basic-HTML-Widget funktioniert nicht: Dort soll ich ja "{a:hm-rega.0.5153;a.replace(/,/g,"<br>")}" im HTML-Feld eingeben, aber das verändert den Inhalt überhaupt nicht. 
Was muss ich bitte tun?

**Comment by Baenker** [comment]
Sorry da kann ich nicht heflen. Schon alleine weil mein Script niemals so einen Mist schreiben würde. Zum anderen ist der Datenpunkt an einer Stelle die dafür nicht vorgesehen ist.

**Comment by MichaelSchaaf999** [comment]
Aaaaaah: Vermutlich hab ich dann da was durcheinandergebracht. 'tschulligung.
Dann hab ich wohl ein anderes Script, dass die CCU-Servicemeldungen für den iOBroker liefert. 
Mea culpa.

Aber ich hab hier keinen Hinweis gefunden, wie und wo man das Script installieren soll: In einem Programm auf der CCU? Fand ja "nur" den Satz "Vor dem Starten des Scripts sollte man die Konfiguration einmal durchgucken" - das fand ich auch erstmal etwas vage.
Also für einen Hinweis, wo da mehr Infos stehen oder wie man vorgehen muss, wäre ich sehr dankbar.

**Comment by Baenker** [comment]
Das Script wird in ioBroker genutzt. Am Anfang des Scripts gibt es eine Konfiguration, die man anpassen muss z. B. welche Datenpunkte beschrieben werden sollen usw. Das Script ist eher nicht für Anfänger. Man sollte sich schon etwas in ioBroker auskennen und mit Scripten umgehen können

**Comment by MichaelSchaaf999** [comment]
Danke sehr für diese Hinweise.

Ich geb mir Mühe, aber es bleiben ein paar wenige Fragen offen:

Ich habe geändert:
     118 const autoAck = false;
Dies sollte erstmal ohne Belang sein.

Aber was pflegt man denn hier (#143ff) sinnvollerweise ein? Datenpunkte, in die geschrieben werden soll?
Muss man die im iOBroker vorher selber anlegen?
In den lines 172 und folgende finde ich doch iOBroker-Datenpunkte, die das Script benötigt, also vermutlich selber anlegt...

143 //Variablen für Servicemeldung in Objekt schreiben // Wenn einer Meldung auftritt wird diese in ein Textfeld geschrieben. z. B. für vis
144 const write_message = false;        // true schreibt beim auftreten einer Servicemeldung die Serviemeldung in ein Objekt
145 const id_Text_Servicemeldung = '';  // Objekt wo die Servicemeldung hingeschrieben werden soll (String)

Und was ist hiermit: Muss ICH da was anlegen? Wenn ja, was?
171 //Müssen selber als Zahl angelegt werden

**Comment by Baenker** [comment]
Die Datenpunkte müssen selber angelegt werden. Wo? Das bleibt jeden selbst überlassen. Die Frage ist auch welche Felder werden benötigt? Wenn ich was nicht benötige lege ich kein Feld an.
Die Datenpunkte müssen sinnvoll angelegt werden also dort wo man eine Zahl erwartet als Zahl, da wo Text als Text.
Und wie ich die Felder benenne bleibt auch mir überlassen. Ich kann das Feld für Anzahl der Servicemeldungen z. B. Aussentemperatur nennen. Ob das Sinnvoll ist? Wohl eher nicht also würde ich das Feld Anzahl_Servicemeldungen nennen.Logischerweise als Zahl.

**Comment by MichaelSchaaf999** [comment]
Danke.

Bleibt als letzte Frage: Geht es um DIESE Datenfelder?

_//Ergebnis in Datenfelder schreiben
const write_state = true;          //Schreibt die Ergebnisse der Servicemeldungen in Datenfelder. (true = schreiben, false, kein schreiben)
//nicht benutzte Felder einfach leer lassen --> var id_IST_XXX = '';
//Müssen selber als Zahl angelegt werden
const id_IST_LOWBAT = '0_userdata.0.Haus.Servicemeldungen.Anzahl_LowBat'/*Anzahl LowBat*/;
const id_IST_LOW_BAT = '';
const id_IST_UNREACH = '0_userdata.0.Haus.Servicemeldungen.Anzahl_Unreach'/*Anzahl Unreach*/;
const id_IST_STICKY_UNREACH = '0_userdata.0.Haus.Servicemeldungen.Anzahl_Sticky_Unreach'/*Anzahl Sticky Unreach*/;
const id_IST_CONFIG_PENDING = '';
const id_IST_UPDATE_PENDING = '';
const id_IST_DEVICE_IN_BOOTLOADER = '';
const id_IST_ERROR = '';
const id_IST_ERROR_NON_FLAT_POSITIONING = '';
const id_IST_ERROR_CODE = '';
const id_IST_FAULT_REPORTING = '';
const id_IST_SABOTAGE = '';
const id_IST_Gesamt = '0_userdata.0.Haus.Servicemeldungen.Anzahl_Gesamt'/*Anzahl Gesamt*/;_

Denn da stehen doch zumindest teilweise schon Namen drin, also bpsw "0_userdata.0.Haus.Servicemeldungen.Anzahl_Unreach" für unreach.
Insofern ist das evtl missverständlich.

**Comment by Baenker** [comment]
Die die das Script nutzen haben es anscheinend verstanden…

Die Felder sind gefüllt weil ich genau diese nutze (die die leer sind nutze ich nicht). Trotzdem muss man die entweder selber anlegen oder eben löschen also mit den zwei Hochstrichen ersetzen. Wenn man selber andere Felder nutzen will muss man die erstellen und anpassen.

Nutze derzeit das Script aber selber nicht mehr.

**Comment by MichaelSchaaf999** [comment]
Nutzt Du denn eine andere sinnvolle Methode, um an die Servicemeldungen der CCU heranzukommen?
Diese Informationen der CCU sind ja nicht unwichtig und wer will schon einmal am Tag auf die CCU schauen.

**Comment by Baenker** [comment]
Wieso sind die wichtig? Früher habe ich auch gedacht das es wichtig ist. Aber ist es nicht. Ausser ggf Batteriemeldungen. Aber ob ein Gerät mal kurz nicht erreichbar war finde ich mittlerweile nicht wichtig. Was nützt mir die Info? Wenn ich viele Meldungen hätte würde ich an der Ursache arbeiten

**Comment by MichaelSchaaf999** [comment]
Sehr guter Satz, damit gehe ich konform: "Wenn ich viele Meldungen hätte würde ich an der Ursache arbeiten".
Aber dazu muss man natürlich erst die "vielen Meldungen" sehen können. Dazu dient ja eigentlich so ein Script.
Danke für die,  ähm, Hilfe.
