### ISSUE TITLE
Problem bei mehreren email-Instanzen

### ISSUE THREAD

**Issue by TestTestRB** [Baenker/Servicemeldungen-Homematic#29]
Meldungen gehen an alle email-Instanzen raus, also email.0, email.1 etc. Nach Änderung der Sender und Empfänger im Script gehen dann Mails an einen Empfänger aber x der angelegten Instanzen.

**Comment by Baenker** [comment]
Änder mal Zeile 234 von email in email.0

**Comment by TestTestRB** [comment]
Hallo,

war der Meinung, dass ich als erstes ausprobiert hätte. Dem ist aber nicht so, da es jetzt funktioniert.
Danke für die schnelle Hilfe.


Von: Baenker ***@***.***>
Gesendet: Sonntag, 25. Dezember 2022 08:48
An: Baenker/Servicemeldungen-Homematic ***@***.***>
Cc: TestTestRB ***@***.***>; Author ***@***.***>
Betreff: Re: [Baenker/Servicemeldungen-Homematic] Problem bei mehreren email-Instanzen (Issue #29)


Änder mal Zeile 234 von email in email.0

-
