### ISSUE TITLE
Batteriewarnmeldung wird sehr oft gesendet

### ISSUE THREAD

**Issue by Binkeldinkel** [Baenker/Servicemeldungen-Homematic#31]
Hallo,
Vorab mal vielen Dank für das tolle Script.
Das einzige was mich stört ist das mir zB. eine Batteriemeldung 36x am Tag (also eigentlich immer wenn sich das Gerät bei der CCU meldet) per Telegram zugesendet wird.

Gibt es da eventuell eine Möglichkeit dass mit einer Variable im Script umzustellen. Das etwa nur neue Meldungen per Telegram versendet werden?

Danke
Schönen Abend

**Comment by Baenker** [comment]
Ich habe keine Möglichkeit gefunden das zu unterbinden. Genau das stört mich auch weshalb ich das Script nicht mehr nutze
