### ISSUE TITLE
Wann sendet das Script?

### ISSUE THREAD

**Issue by vr6syncro** [Baenker/Servicemeldungen-Homematic#4]
Moin, wollte wissen wann das Script sendet. Weil bei mir kommt eine Servicemeldung extrem oft teilweise 4x die Stunde. 

Gruß Alex

**Comment by Baenker** [comment]
Es sendet sobald eine Servicemeldung auftritt.  Es besteht die Möglichkeit einzelne Geräte aus der Überwachung zu nehmen.

Um welche Servicemeldung handelt es sich denn genau? Und ist es immer die gleiche. Erledigt sich die Meldung erst und kurze Zeit später kommt die Meldung wieder?

**Comment by vr6syncro** [comment]
ok danke für die infos... bin mir nicht mal sicher ob es überhaupt was mit dem script an sich zutun hat. es kommen bei mir öfter mal meldungen mehrfach.

Welche Meldung kommt ist eigentlich egal. Es sieht so aus als ob der Trigger bei mir öfter als ein mal auslösen würde. 

Also ich bekomme die Meldung was ja korrekt ist. Dann kommt aber oftmals paar minuten/stunden nochmals und nochmals die Meldung. Das aber völlig unvorhersehbar un reproduzierbar. Das letzte mal kam es 4 mal auf der Arbeit ca. 2 Stunden lang und seitdem nicht wieder. Servicemeldung besteht aber immer noch. Ist ne lowbatt vom Heizungsthermostat hab ich noch nicht gewechselt.

**Comment by Baenker** [comment]
Es ist schon entscheidend um welche Servicemeldung es geht. Bei Lowbat sollte das nicht passieren.

Welche Version nutzt Du? Bitte auf jeden Fall mal die aktuelle nutzen damit darf das auf keinen Fall passieren. Falls doch musst Du nur ins Log gucken. Ich protokolliere eigentlich alles was passiert und somit siehst Du auch woran es liegen könnte.

Beispiel: Ein Gerät hat eine LowBat Meldung dann bekommt man sofort die Push. Sollte z. B. 10 Minuten später eine weitere Servicemeldung (egal von welchen Gerät) kommen. Hättest Du vermutlich mit einer alten Version 2 Pushmitteilungen bekommen. Einmal die schon bekannte LowBat und einmal die neue.
Beim neuen Script sollte es dann nur eine geben in der beide Meldungen stehen. Verschwindet die andere bekommst Du im alten auf jeden Fall wieder eine Push über LowBat in der aktuellen Version sollte dort gar keine Meldung kommen.

**Comment by vr6syncro** [comment]
ok da muss ich etwas warten bis ich mal wieder eine neue meldung/fehlerbild bekomme.
