### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by vr6syncro** [Baenker/Servicemeldungen-Homematic#5]
Moin, ich bekomme einen Error beim ausführen des Scriptes. Ich habe noch keine Änderungen im Setup durchgeführt.

`

javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) at Script.runInContext (vm.js:133:20)
-- | -- | -- | --
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) at script.js.User.Homematic.Servicemeldungen:2050:5
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) at Servicemeldung (script.js.User.Homematic.Servicemeldungen:744:21)
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:808:29)
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) at script.js.User.Homematic.Servicemeldungen:745:74
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) TypeError: Cannot read property 'common' of null
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) ^
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) common_name = getObject(id.substring(0, id.lastIndexOf('.') - 2)).common.name;
javascript.0 | 2019-10-21 14:08:06.893 | error | (17498) script.js.User.Homematic.Servicemeldungen: script.js.User.Homematic.Servicemeldungen:745
javascript.0 | 2019-10-21 14:08:06.892 | warn | (17498) Object "hm-rpc.0.000C170999F19D" does not exist

`

**Comment by Baenker** [comment]
Was ist das für ein Gerät: hm-rpc.0.000C170999F19D?

Bitte mal auf das Gerät filtern und auf +.ALRAMS. Was für Treffer gibt es? Sind all die Felder befüllt?

**Comment by vr6syncro** [comment]
Das ist ein HM IP Präsenzmelder. Warum der unter rpc.0 instanz steht weiß ich aber nicht, dort gehört er nicht hin. Habe ihn nun mal gelöscht und es scheint wieder zu laufen.

Beobachte es mal weiter. Danke für die Hilfe
