### ISSUE TITLE
Keine Servicemeldungen werden angezeigt

### ISSUE THREAD

**Issue by fraeggle** [Baenker/Servicemeldungen-Homematic#6]
Hi.
Irgendwie hab ich ein kleines Problem.
Das Script zeigt mir immer "Keine Servicemeldungen" an, obwohl ich z.B. einen kommunikationsfehler hab.
Das Script hab ich entsprechend angepasst (Datenpunkte angelegt..):

Pushover,Telegramm,Sendmail auf false.
Folgendes angepasst
//Variablen für Servicemeldung in Objekt schreiben 
// Wenn einer Meldung auftritt wird diese in ein Textfeld geschrieben. z. B. für vis
const write_message = true;        // true schreibt beim auftreten einer Servicemeldung die Serviemeldung in ein Objekt
const id_Text_Servicemeldung = 'javascript.0.Servicemeldungen.Servicemeldungen';  // Objekt wo die Servicemeldung hingeschrieben werden soll (String)

const write_state = true;          //Schreibt die Ergebnisse der Servicemeldungen in Datenfelder. (true = schreiben, false, kein schreiben)
//nicht benutzte Felder einfach leer lassen --> var id_IST_XXX = '';
//Müssen selber als Zahl angelegt werden
const id_IST_LOWBAT = 'javascript.0.Servicemeldungen.Anzahl_LOWBAT'/*Anzahl LOWBAT*/;
const id_IST_UNREACH = 'javascript.0.Servicemeldungen.Anzahl_UNREACH'/*Anzahl_UNREACH*/;
const id_IST_STICKY_UNREACH = 'javascript.0.Servicemeldungen.Anzahl_STICKY_UNREACH'/*Anzahl_STICKY_UNREACH*/;
const id_IST_Gesamt = 'javascript.0.Servicemeldungen.Anzahl_GESAMT'/*Anzahl_GESAMT*/;

Im Logging sehe ich folgendes:
![Fehler1](https://user-images.githubusercontent.com/40692505/76144996-c0377c00-6085-11ea-8163-db12cd4784bf.JPG)
Unter javascript.0. sind folgende Punkte:
![grafik](https://user-images.githubusercontent.com/40692505/76145016-e826df80-6085-11ea-97a7-4e73c5df4053.png)

Was mach ich falsch?
Gruß Peter

**Comment by Baenker** [comment]
Benutzt Du cuxd?

**Comment by fraeggle** [comment]
ich hab cuxd in der CCU ja... aber in dem script hab ich das auf 9 stehen gelassen..

**Comment by Baenker** [comment]
Warum hast Du es auf 9 gelassen? Bitte mal die Warnings im Log durchlesen...

**Comment by fraeggle** [comment]
hmm ok versteh... "Script wird gestoppt", richtig? Muss ich dann im IOBroker vermutlich zusätzlich eine RPC Instanz mit CUXD anlegen. Dachte das wäre nicht nötig, da ich nur timer vom CUXD verwende.

**Comment by Baenker** [comment]
Jetzt wird es interessant. Du hast keine Cuxd Instanz im ioBroker? Dann geh mal in die Objekte und Filter nach „cux“. Was siehst Du? Ich vermute mal das dort cuxd-Geräte sind die dann dort nicht hingehören. Grundsätzlich ist 9 richtig wenn Du keine Instanz hast. Das Problem ist das das Script nach „cux“ sucht in den Geräten. Wenn es etwas findet bricht es ab und somit wird nicht das komplette Script abgearbeitet.

**Comment by fraeggle** [comment]
![grafik](https://user-images.githubusercontent.com/40692505/76145643-9f722500-608b-11ea-8a03-f32a914685c0.png)
wie filter ich bei objekte nac cux?

**Comment by fraeggle** [comment]
ÄH  IOBroker neu gestartet........  Kein Fehler mehr und Servicemeldungen werden auch angezeigt...

Muss ich nicht verstehen........
Ich schließ das wieder......  ABER  danke für deine unterstützung... und auch danke für das geniale Script  :-D
