### ISSUE TITLE
Fehler im Log

### ISSUE THREAD

**Issue by totocotonio** [Baenker/Servicemeldungen-Homematic#7]
Beim starten des Scripts kommt folgende Meldung im Log und das Script bleibt gelb.

javascript.0 | 2020-06-16 09:34:51.171 | error | (21203) at Script.runInContext (vm.js:131:20)
-- | -- | -- | --
javascript.0 | 2020-06-16 09:34:51.171 | error | (21203) at script.js.common.Service.Servicemeldung_der_ccu:2185:5
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) at Servicemeldung (script.js.common.Service.Servicemeldung_der_ccu:814:21)
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:796:29)
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) at script.js.common.Service.Servicemeldung_der_ccu:816:67
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) TypeError: Cannot read property 'common' of null
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) ^
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) if(getObject(id.substring(0, id.lastIndexOf('.') - 2)).common.name){
javascript.0 | 2020-06-16 09:34:51.170 | error | (21203) script.js.common.Service.Servicemeldung_der_ccu: script.js.common.Service.Servicemeldung_der_ccu:816

**Comment by Baenker** [comment]
Bitte Script stoppen. Java-Instanz stoppen danach alle Homematic Instanzen stoppen.

Unter Objekte alle HM-Geräte löschen. Danach die Homematic Instanzen starten, danach Java und zum Schluß das Script neu starten.

Falls das nicht hilft brauche ich mehr Infos. Welche Geräte? hm oder hmip oder beide? Cuxd?

**Comment by totocotonio** [comment]
So alles gemacht, immer noch der gleiche Fehler

**Comment by Baenker** [comment]
Wie oben schon geschrieben: Falls das nicht hilft brauche ich mehr Infos. Welche Geräte? hm oder hmip oder beide? Cuxd?

Und ganz wichtig. Bitte das gesamte Log. Ich vermisse einen Eintrag vom Script der zumindest mal die Konfig zeigt...

Ziemlich weit oben im Script gibt es ein Debug = false; ändern in true und speichern. Danach das Log bitte.

**Comment by totocotonio** [comment]
Also es handelt sich um HM Geräte.



javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) at Script.runInContext (vm.js:131:20)
-- | -- | -- | --
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) at script.js.common.Service.Servicemeldung_der_ccu:2185:5
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) at Servicemeldung (script.js.common.Service.Servicemeldung_der_ccu:1213:22)
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:796:29)
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) at script.js.common.Service.Servicemeldung_der_ccu:1214:74
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) TypeError: Cannot read property 'common' of null
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) ^
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) common_name = getObject(id.substring(0, id.lastIndexOf('.') - 2)).common.name;
javascript.0 | 2020-06-16 13:39:49.037 | error | (1610) script.js.common.Service.Servicemeldung_der_ccu: script.js.common.Service.Servicemeldung_der_ccu:1214
javascript.0 | 2020-06-16 13:39:49.036 | warn | (1610) Object "hm-rpc.0.000AD5699C66EC" does not exist
javascript.0 | 2020-06-16 13:39:49.036 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: [DEBUG] id_IST Feld für STICKY_UNREACH nicht gefüllt
javascript.0 | 2020-06-16 13:39:49.036 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Es gibt: 51 Geräte mit dem Datenpunkt STICKY_UNREACH.
javascript.0 | 2020-06-16 13:39:49.034 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Keine Geräte gefunden mit dem Datenpunkt UNREACH.
javascript.0 | 2020-06-16 13:39:49.034 | warn | (1610) script.js.common.Service.Servicemeldung_der_ccu: [Script wird gestoppt] Der Datenpunkt hm-rpc.0.000AD5699C66EC.0.UNREACH_ALARM existiert nicht.
javascript.0 | 2020-06-16 13:39:49.034 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Keine Geräte gefunden mit dem Datenpunkt LOW_BAT.
javascript.0 | 2020-06-16 13:39:49.034 | warn | (1610) script.js.common.Service.Servicemeldung_der_ccu: [Script wird gestoppt] Der Datenpunkt hm-rpc.0.000AD5699C66EC.0.LOW_BAT_ALARM existiert nicht.
javascript.0 | 2020-06-16 13:39:49.034 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: [DEBUG] id_IST Feld für LOWBAT nicht gefüllt
javascript.0 | 2020-06-16 13:39:49.034 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Es gibt: 45 Geräte mit dem Datenpunkt LOWBAT.
javascript.0 | 2020-06-16 13:39:49.031 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Script manuell gestartet. (Version: 1.73)
javascript.0 | 2020-06-16 13:39:48.447 | info | (1610) Start javascript script.js.common.Service.Servicemeldung_der_ccu
javascript.0 | 2020-06-16 13:39:46.520 | info | (1610) Stop script script.js.common.Service.Servicemeldung_der_ccu
javascript.0 | 2020-06-16 13:38:40.162 | error | (1610) at Script.runInContext (vm.js:131:20)
javascript.0 | 2020-06-16 13:38:40.162 | error | (1610) at script.js.common.Service.Servicemeldung_der_ccu:2185:5
javascript.0 | 2020-06-16 13:38:40.162 | error | (1610) at Servicemeldung (script.js.common.Service.Servicemeldung_der_ccu:1213:22)
javascript.0 | 2020-06-16 13:38:40.162 | error | (1610) at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:796:29)
javascript.0 | 2020-06-16 13:38:40.161 | error | (1610) at script.js.common.Service.Servicemeldung_der_ccu:1214:74
javascript.0 | 2020-06-16 13:38:40.161 | error | (1610) TypeError: Cannot read property 'common' of null
javascript.0 | 2020-06-16 13:38:40.161 | error | (1610) ^
javascript.0 | 2020-06-16 13:38:40.161 | error | (1610) common_name = getObject(id.substring(0, id.lastIndexOf('.') - 2)).common.name;
javascript.0 | 2020-06-16 13:38:40.161 | error | (1610) script.js.common.Service.Servicemeldung_der_ccu: script.js.common.Service.Servicemeldung_der_ccu:1214
javascript.0 | 2020-06-16 13:38:40.159 | warn | (1610) Object "hm-rpc.0.000AD5699C66EC" does not exist
javascript.0 | 2020-06-16 13:38:40.159 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: [DEBUG] id_IST Feld für STICKY_UNREACH nicht gefüllt
javascript.0 | 2020-06-16 13:38:40.158 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Es gibt: 51 Geräte mit dem Datenpunkt STICKY_UNREACH.
javascript.0 | 2020-06-16 13:38:40.156 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Keine Geräte gefunden mit dem Datenpunkt UNREACH.
javascript.0 | 2020-06-16 13:38:40.156 | warn | (1610) script.js.common.Service.Servicemeldung_der_ccu: [Script wird gestoppt] Der Datenpunkt hm-rpc.0.000AD5699C66EC.0.UNREACH_ALARM existiert nicht.
javascript.0 | 2020-06-16 13:38:40.156 | info | (1610) script.js.common.Service.Servicemeldung_der_ccu: Keine Geräte gefunden mit dem Datenpunkt LOW_BAT.
javascript.0 | 2020-06-16 13:38:40.155 | warn | (1610) script.js.common.Service.Servicemeldung_der_ccu: [Script wird gestoppt] Der Datenpunkt hm-rpc.0.000AD5699C66EC.0.LOW_BAT_ALARM existiert nicht.


Mehr kommt nicht im LOG

**Comment by Baenker** [comment]
Was ist denn "hm-rpc.0.000AD5699C66EC" Bei dem Gerät gibt es nicht die Felder?

Wie ist der Rega Adapter konfiguriert?

Das Gerät ist doch kein HM? Ist doch eher hmip?

**Comment by totocotonio** [comment]
Das gerät was es immer es auch ist erscheint nicht in den Objekten.

Keine Ahnung wo das herkommt.

Vielleicht ein Fragment aus einer alten installation

**Comment by Baenker** [comment]
Dieses Objekt verursacht den Fehler. Normalerweise reicht es das Script zu stoppen und die Java-Instanz zu stoppen. Wenn dann alles wieder gestartet wird sollte es gehen. Ggf auch ioBroker mal neu starten.

Von Namen ist es ein hm-ip Gerät. Deshalb könnte auch eine fehlerhafte Konfig vom hm-rega Adapter das Problem sein. 

Mehr kann ich leider nicht tun.

**Comment by totocotonio** [comment]
Ja kann sein ich aber aber kein IP Gerät.


Lustig hast noch eine Idee wich das weg bekomme.

**Comment by Baenker** [comment]
Da das Problem nicht am Script liegt, sondern an der Installation bzw dem Objekt "hm-rpc.0.000AD5699C66EC" mache ich hier zu.
