### ISSUE TITLE
Fehlender Batterietyp Thermostat HmIP-eTRV-C

### ISSUE THREAD

**Issue by Wildbill-Z** [Baenker/Servicemeldungen-Homematic#8]
Hi,

ich habe drei von den kompakten Homematic-IP-Heizungsreglern HmIP-eTRV-C in Betrieb und anscheinend kennt Dein Script die noch nicht. Ich bekomme für jeden immer folgende Meldung:

`
javascript.0 | 2020-09-09 10:33:53.801 | info | (15838) script.js.Benachrichtigung.HM-Servicemeldungen: Bitte melden: Treppenhaus_Heizkörper (00119A499618AC) --- HmIP-eTRV-C --- Batterietyp fehlt im Script
-- | -- | -- | --
`
Wäre nett, wenn Du die noch hinzufügen könntest.

Gruss, Jürgen

**Comment by Baenker** [comment]
ist in der neuen Version aufgenommen
