### ISSUE TITLE
Keine Meldungen mehr ab iobroker Javascript Adapter Version 4.9.0

### ISSUE THREAD

**Issue by spaceduck518** [Baenker/Servicemeldungen-Homematic#9]
Nach Update des Javascript Adapters auf 4.9.0 bzw. 4.9.3 bleiben trotz anstehender Servicemeldungen die Datenpunkte auf "0".
Ein Downgrade auf Javascript Adapter Version 4.8.4 und das Script funzt wieder.

**Comment by Baenker** [comment]
Das ist bekannt. Das Scipt ist in dieser Version nicht für die Beta-Version vom javascript Adapter kompatibel. Einfach bei den Selektoren hinten das $ weg machen dann geht es.
